#!/bin/bash
sudo apt-get install -y curl ccache build-essential \
    bison flex cmake meson \
    autoconf autoconf-archive automake autopoint libtool \
    git xmltoman docbook-utils swig doxygen

# for Python 3.7
sudo apt-get install -y libssl-dev libffi-dev

# for libid3tag
sudo apt-get install -y gperf

# for lxml
sudo apt-get install -y libxml2-dev

# for glib-dbus-1.0
sudo apt-get install -y libdbus-glib-1-dev
