#!/bin/sh -e

DBG_ARCH=${DBG_ARCH:-aarch64}
DBG_PORT=${DBG_PORT:-10101}
DBG_EXEC=${1}
shift 1
DBG_EXEC_PARAMS="${@}"

if [ -z ${DBG_EXEC} ]
then
	echo "Usage:"
	echo
	echo "$(basename ${0}) <chroot_cmd> <sysroot_path>"
	echo
	exit 1
fi

export QEMU_LD_PREFIX=${SYSROOT}

echo "Command to debug: ${DBG_EXEC} ${DBG_EXEC_PARAMS}"
echo "Target architecture: ${DBG_ARCH}"
echo
echo -n "Running command in debug mode..."
nohup qemu-${DBG_ARCH}-static -g ${DBG_PORT} ${SYSROOT}${DBG_EXEC} ${DBG_EXEC_PARAMS} &
echo -e " ok.\n"

cat >/tmp/batch.gdb <<-EOF
	set debuginfod enabled on
	set architecture ${DBG_ARCH}
	set sysroot ${SYSROOT}
	exec-file ${SYSROOT}${DBG_EXEC}
	target remote :${DBG_PORT}
	continue
	backtrace
	quit
EOF
gdb --batch --command=/tmp/batch.gdb
rm nohup.out /tmp/batch.gdb
