#!/bin/bash

# Requires at least one OPTS or OPTS_WITH_VALUE to run

OPTS+=" -v"
NUM=0

for p in $(( set -o posix ; set ) | grep ^_param_)
do
	unset $(echo $p | awk 'BEGIN {FS="="} ; {print $1}')
done

while(($#)) ; do
	if [ "${1}" == "$(echo ${OPTS} ${OPTS_WITH_VALUE} | grep -o -- "${1}\b")" ]
		then
			OPTION=${1}
			PARAMETER=$(echo ${1} | sed -e 's/^--\?//')
			if [ "${1}" == "$(echo ${OPTS_WITH_VALUE} | grep -o -- "${1}\b")" ]
			then
				shift
				if [ ! x${1} == x ]
				then 
					eval "_param_${PARAMETER}='${1}'"
				else
					echo "${OPTION} unset, no assigned value."
					exit 1
				fi
			else
				eval "_param_${PARAMETER}=1"
			fi
	else
		if [[ ${1} == -* ]]
		then
			echo "Unrecognized option: ${1}"
			exit 1
		else
			NUM=$((NUM+1))
			eval "_param_${NUM}=${1}"
			PARAMETER=${NUM}
		fi
	fi
	[ ${_param_v:-0} -eq 1 ] && eval echo "_param_${PARAMETER}=\$_param_${PARAMETER}" || true
	shift
done
