name: Docker Build and Push

on:
  push:
    branches:
      - development
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'
  pull_request:
    branches: 
      - development
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # Required for OIDC

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment: Development
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      if: ${{ vars.REPO_SERVICE == 'aws_ecr' }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: GithubActionsOIDC
        aws-region: ${{ vars.AWS_REGION }}

    - name: Login to Amazon ECR
      if: ${{ vars.REPO_SERVICE == 'aws_ecr' }}
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Login to Docker Hub
      if: ${{ vars.REPO_SERVICE == 'dockerhub' || vars.REPO_SERVICE == '' }}
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_USERPASSWD }}

    - name: Extract version from tag
      id: get_version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        fi

    - name: Set repository variables
      id: repo_vars
      run: |
        if [ "${{ vars.REPO_SERVICE }}" = "aws_ecr" ]; then
          echo "repository=${{ steps.login-ecr.outputs.registry }}/${{ vars.AWS_ECR_REPOSITORY }}" >> $GITHUB_OUTPUT
        else
          # Default to Docker Hub if REPO_SERVICE is not set or is set to dockerhub
          echo "repository=${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY || 'bbcrossbuild' }}" >> $GITHUB_OUTPUT
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ steps.repo_vars.outputs.repository }}
        tags: |
          type=sha,format=short
          type=ref,event=branch
          type=ref,event=tag
          type=raw,value=latest,enable=${{ github.ref == format('refs/tags/{0}', github.event.repository.default_branch) }}
    
    - name: Build, tag, and push image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Clean up
      if: always()
      run: |
        docker system prune -f
